### ISSUE TITLE
Homey SDK3 support

### ISSUE THREAD

**Issue by RonnyWinkler** [mskg/homey-heating#171] opened 2022-10-16 09:17 UTC
Hello Markus,

Athom has announced the HomeyPro Early 2023. 
This new device only supports SDK3. And perhaps all SDK2 apps will be hidden in the app store since 01.01.2023.

Can/will you upgrade this very helpful app to SDK3?
I you are not willing to continue app support, would you pass the app to a new owner to continue?
Many thanks in advance for your feedback :-)

Kind regards
Ronny

**Comment by mskg** [comment] 2022-10-16 09:28
No, I will upgrade it.

**Comment by RonnyWinkler** [comment] 2022-10-16 09:31
Sounds good. Many thanks.
Perhaps you could add your app to the "in progress list", so users (like me) are calmed down :-)
https://community.homey.app/t/homey-pro-early-2023-app-unsupported-list/70324

**Comment by mskg** [comment] 2022-10-16 09:57
I have no clue how that community pages work 😃 Are you able to add the status for me? That would be great.

**Comment by RonnyWinkler** [comment] 2022-10-16 10:00
Sure. I will do.
Btw. It would be nice if you could add a condition "heating plan is active (yes/no"). That would be a nice addition.

**Comment by mskg** [comment] 2022-10-16 10:04
That's not a big thing, will do that

**Comment by daneedk** [comment] 2022-10-16 11:02
Great to see your support Markus, thanks!

**Comment by RonnyWinkler** [comment] 2022-12-31 08:48
Hi Markus, 
do you have an update or ETA for SDK3 support? 
On current Homey, the app will still work. But from tomorrow it won't be available in te app store.
Thanks 
Ronny

**Comment by shaarkys** [comment] 2023-01-27 12:04
Luckily it's still available - https://homey.app/en-us/app/app.mskg.homey-heating/Homey-Heating-Scheduler/

**Comment by RonnyWinkler** [comment] 2023-01-27 12:53
Still visible, but will be hidden in the next weeks because the app is still on SDK2.

**Comment by shaarkys** [comment] 2023-01-27 13:47
Yep, that's why I wrote "luckily"...but hopefully @mskg Markus is still somehow on it.

**Comment by RonnyWinkler** [comment] 2023-02-02 22:52
Hi Markus,
do you have some news for us? 
Homey 2023 is in delivery for developers now. So it would be greate to be able to use your app on that device - with SDK3 update.

Regards
Ronny

**Comment by mskg** [comment] 2023-02-03 12:09
Good news for your gents, received the brand new device today. Will try to make it quick for all of you ...

**Comment by shaarkys** [comment] 2023-03-19 18:22
> Good news for your gents, received the brand new device today. Will try to make it quick for all of you ...

Hi Markus, @mskg 

would you mind please to share some update with us ? I don't know how much complex the rewrite is so just asking not on ETA but rather kind of expectation setting.

Thank you 😊

**Comment by rlucian** [comment] 2023-03-23 17:32
The new HP23 is so much better than the old one, so I expect most people that get it to switch and unplug the old device, as I just did. Unfortunately, your awesome app was one of the very few that doesn't work on sdkv3 yet, not even with a test version.  
It would be highly appreciated if you could share some expectations with us, so we know whether we should wait a bit or use some alternate solutions.

If you accept a contributor to help out with the refactoring, I can find (and pay for it myself) someone more skilled than me to assist.

**Comment by hetlelid** [comment] 2023-03-29 18:58
Hi Markus.

Thanks for the awesome app! Looking forward to see it in SDK3 version :) Let us know if there is any challenges along the road.

**Comment by mskg** [comment] 2023-04-16 17:43
https://homey.app/a/app.mskg.homey-heating/test/

Known issues:
- Help link doesn't open
- Navigating forth and back to "Current temperatures" crashes the frontend on the third try

**Comment by mskg** [comment] 2023-04-16 17:44
Duplicate of #173 -> closing this

**Closed as completed by mskg** 2023-04-16 17:44 UTC
Labels: enhancement
